name: unifi-proxy

namespace: unifi-proxy

deployment:
  - name: unifi-proxy
    image: nginx
    ports:
    - port: 80
    volumes:
      - name: nginx-settings
        type: config
        path: /etc/nginx/conf.d/

service:
  clusterIP:
    - name: unifi-proxy
      selector: unifi-proxy
      ports:
      - port: 80

configmap: 
  - name: nginx-settings
    file: config/proxy.conf

ingress:
  - name: unifi-proxy
    selector: unifi-proxy
    path: /
    port: 80
    host: unifi.kavanet.io